

# GET start
GET http://localhost:3001/

# GET info
GET http://localhost:3001/info

# GET persons api
GET http://localhost:3001/api/persons

# GET persons api with id
GET http://localhost:3001/api/persons/3

# DELETE
DELETE http://localhost:3001/api/persons/8

# POST
POST http://localhost:3001/api/persons
Content-Type: application/json
{
   "name": "Lisa Simpson",
   "number": "555-29509"
}