

# GET start
GET http://localhost:3001/

# GET info
GET http://localhost:3001/info

# GET persons api
GET http://localhost:3001/api/persons

# GET persons api with id
GET http://localhost:3001/api/persons/5ead233e7fc1a71f72c69cff

# DELETE
DELETE http://localhost:3001/api/persons/5ead3fd2e429e0220074da88

# POST
POST http://localhost:3001/api/persons
Content-Type: application/json
{
   "name": "Li",
   "number": "5559"
}

# PUT
PUT http://localhost:3001/api/persons/5ead3ff9e429e0220074da89
Content-Type: application/json
{
   "name": "Lisa Simpson",
   "number": "555-6"
}


# heroku GET
GET https://floating-ocean-90630.herokuapp.com/

# GET persons api
GET http://floating-ocean-90630.herokuapp.com/api/persons

# GET persons api with id
GET http://floating-ocean-90630.herokuapp.com/api/persons/3

# DELETE
DELETE http://floating-ocean-90630.herokuapp.com/api/persons/8

# POST
POST http://floating-ocean-90630.herokuapp.com/api/persons
Content-Type: application/json
{
   "name": "Lisa Simpson",
   "number": "555-29509"
}
