
POST http://localhost:3001/api/patients
Content-Type: application/json
{
        "name": "Oliver Sachs II",
        "dateOfBirth": "2010-06-10",
        "ssn": "0933-336-122X",
        "gender": "male",
        "occupation": "Film Director's Double"
}

#
GET http://localhost:3001/api/patients
